### ISSUE TITLE
Problems with Depth Cache

### ISSUE THREAD

**Issue by elject** [jaggedsoft/node-binance-api#33]
I've been running Depth Cache for a while now. And the code broke two times, these are the errors:
```
 node-binance-api.js:280
 
                 for ( obj of depth.b ) { //bids
                                    ^
 TypeError: depth.b is not iterable
```

```
node-binance-api.js:603
                 for ( let depth of messageQueue[symbol] ) {
                                                ^

TypeError: messageQueue[symbol] is not iterable
```
I think Depth Cache has some issues at the moment. Or is it my fault? This is the code I'm using
```
binance.websockets.depthCache(socketArray, function(symbol, depth) {
	let bids = binance.sortBids(depth.bids);
	let asks = binance.sortAsks(depth.asks);
	let bid = binance.first(bids);
	let ask = binance.first(asks);
	prices[symbol] = prices[symbol] || {}
	prices[symbol].ask = parseFloat(bid),
	prices[symbol].bid = parseFloat(ask)
});
```

**Comment by jaggedsoft** [comment]
Thank you for the report! More error handling will be added

**Comment by elject** [comment]
Also, don't know if this helps, but this usually happens when a socket is reconnecting.
For example:
`WebSocket reconnecting: ethbtc@depth`

**Comment by jaggedsoft** [comment]
Yes thank you, that absolutely helps. That tells me the problem is when it is unable to reconnect the first time. So now we should be able to tell it to keep trying to reconnect until it works

Did this happen last night when binance went down?

> The problem is with /depth (request) not @depth (websocket)

**Comment by elject** [comment]
It happened today few times. Not sure why but there are moments when socket connections go down. Probably due to the moments when there are high loads on Binance servers.

**Comment by jaggedsoft** [comment]
Thanks. I intend to fix this as soon as I can. I'm behind on some projects right now so it will take me a bit to get caught up

**Comment by jsappme** [comment]
This issue might be related to my `WebSocket connection closed!` problems. @jaggedsoft you are doing a great job!

**Comment by josepgomes** [comment]
Hi,

Don't know if this is the perfect way to correct this problem, but can help a lot of people until official fix is released:

line 603

```javascript
info[symbol].firstUpdateId = json.lastUpdateId;
depthCache[symbol] = depthData(json);
for ( let depth of messageQueue[symbol] ) {
    depthHandler(depth, json.lastUpdateId);
}
delete messageQueue[symbol];
if ( callback ) callback(symbol, depthCache[symbol]);
```
To

```javascript
if (messageQueue != null && typeof messageQueue[symbol] === 'object') {
    info[symbol].firstUpdateId = json.lastUpdateId;
    depthCache[symbol] = depthData(json);
    for ( let depth of messageQueue[symbol] ) {
        depthHandler(depth, json.lastUpdateId);
    }
    delete messageQueue[symbol];
    if ( callback ) callback(symbol, depthCache[symbol]);
}
```

**Comment by jaggedsoft** [comment]
Thank you very much @josepgomes 
If that code is tested and working I can include it in the next release

**Comment by AlessandroSpallina** [comment]
when will be added this fix in the library?

**Comment by jaggedsoft** [comment]
I haven't had time to test it yet. I was hoping @josepgomes would respond if it is working properly & resolved

**Comment by josepgomes** [comment]
The 'if' that i added revolved completely the issue in my software. We are still developing using this library and the error did not happen again :)

Still, i hope someone test it too! Pretty fast to test it if you already have the request implemented.

**Comment by jaggedsoft** [comment]
Thank you very much! I will push an update right now

**Comment by jaggedsoft** [comment]
Pushing another update which fixes data corruption on reconnect

**Comment by jmarto** [comment]
@jaggedsoft just started using this wrapper - great work! However I am getting this issue still with version 0.4.11.  Rolling back it seems to be introduced in 0.4.9, where i get the following:

`/node_modules/node-binance-api/node-binance-api.js:837`
`for (let depth of messageQueue[symbol])`
`                              ^`
`TypeError: messageQueue[symbol] is not iterable`

**Comment by jaggedsoft** [comment]
@jmarto Thank you very much! This is possible due to contributors like @keith1024 who help keep us going.
Will look in to it.

**Comment by jmarto** [comment]
Thanks!

**Comment by keith1024** [comment]
@jmarto @jaggedsoft I'll have a look at this right now. Will provide updates on my findings as soon as I have any.

**Comment by jmarto** [comment]
Interestingly enough this error doesn't appear when using the package on npm-runkit...

**Comment by jmarto** [comment]
My code was exactly as per the demo.  Reproduced here:

```
const BinanceAPI = require('node-binance-api'); //https://www.npmjs.com/package/node-binance-api
  BinanceAPI.websockets.depthCache(pairArray, (symbol, depth) => {
    let bids = BinanceAPI.sortBids(depth.bids);
    let asks = BinanceAPI.sortAsks(depth.asks);
    console.log(symbol+" depth cache update");
    console.log("best bid: "+BinanceAPI.first(bids));
    console.log("best ask: "+BinanceAPI.first(asks));
  });
```

**Comment by keith1024** [comment]
@jmarto Does a symbol pair perhaps appear more than once in your `pairArray`?

**Comment by jmarto** [comment]
It wasn't. I was initially passing in as per my edit with simply `['XRPBTC','LTCBTC']`. But would you believe that it has just decided to work with v0.4.11?  Can't figure out why, but I'm sure it was my fault.  Sorry to bother!  Thanks for following up so quickly.

**Comment by keith1024** [comment]
Ah great, I'm glad to hear it's working now. The only way I could see to reproduce that error, and my tests confirmed, was to have a duplicate symbol somewhere in that array. So I'll add in logic to avoid that situation, just in case. No bother, it at least helped to discover the above case. :)

**Comment by jmarto** [comment]
@keith1024 Yes you're right. That does in fact reproduce it for me too. 

I went through my undo stack and found the problem again. It turns out I was effectively doing as you said, but to simplify it, I was essentially making two calls to `.depthCache()` for the same symbol, like so:

```
const binance = require("node-binance-api");
function openBinanceSocket() {
  binance.websockets.depthCache(['BNBBTC'], (symbol, depth) => {
    let bids = binance.sortBids(depth.bids);
    let asks = binance.sortAsks(depth.asks);
    console.log(symbol+" depth cache update");
    console.log("best bid: "+binance.first(bids));
    console.log("best ask: "+binance.first(asks));
  });
};
openBinanceSocket();
openBinanceSocket();
```
